# -*- mode: ruby -*-
# vi: set ft=ruby :

# https://www.postgresql.org/docs/9.3/static/libpq-envars.html
PORT=80
FPORT=8080
NODE_VER="8.x"
SCRIPTS_DIR="/home/vagrant/rebelchat-backoffice/scripts/"

# server vars
HOSTNAME = "backoffice"
FQDN = HOSTNAME + "yakchat.io"
#server_cpus   = "1"   # Cores
SERVER_MEMORY = "512" # MB Normally 512MB, raise this to 2048 to compile plv8
SERVER_SWAP   = "1024" # Options: false | int (MB) -
                      # Guideline: Between one or two times the server_memory

                      #Allow us to run both projects in one vagrant by supplying the path to the client repo

$script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = HOSTNAME
  config.vm.network "forwarded_port", guest: PORT, host: FPORT
  config.vm.provider "virtualbox" do |v|
    v.memory = SERVER_MEMORY
    v.customize ["modifyvm", :id, "--memory", SERVER_MEMORY]
  end
  config.vm.provision "shell", inline: $script
  config.vm.synced_folder "../", "/home/vagrant/rebelchat-backoffice", create:true,
    :mount_options => ['dmode=775', 'fmode=777']

 config.vm.provision :shell do |s|
    s.path = "bootstrap.sh"
    s.env = {
      "FQDN" => FQDN,
      "PORT" => PORT,
      "FPORT" => FPORT,
      "SCRIPTS_DIR" => SCRIPTS_DIR,
      "NODE_VER" => NODE_VER
    }
  end

end
