export const AUTH_LOGIN_REJECTED = 'AUTH_LOGIN_REJECTED';
export const AUTH_LOGIN_FULFILLMENT = 'AUTH_LOGIN_FULFILLMENT';
export const AUTH_LOGIN_PROGRESS = 'AUTH_LOGIN_PROGRESS';
export const AUTH_LOGOUT_FULFILLMENT = 'AUTH_LOGOUT_FULFILLMENT';
export const AUTH_LOGOUT_REJECTED = 'AUTH_LOGOUT_REJECTED';
export const AUTH_USER_ALREADY_AUTHENTICATED = 'AUTH_USER_ALREADY_AUTHENTICATED';
